### ISSUE TITLE
g11n-pipeline.uploadStrings error with specific characters

### ISSUE THREAD

**Issue by Setogit** [IBM-Bluemix/gp-js-client#34]
`g11n-pipeline` v1.2.2 and GA Globalization Pipeline on Bluemix service.

The attached JSON strings cases uploadStrings to fail with the following error:
uploadStrings error: {"obj":{"status":"ERROR","message":"Failed to authenticate user: [my credential] 

```
{
  "msgBoxDrawingChars": "└──"
}
```

[boxDrawingChars.txt](https://github.com/IBM-Bluemix/gp-js-client/files/380062/boxDrawingChars.txt)

**Comment by yumaoka** [comment]
The JSON contents above successfully uploaded on Bluemix dashboard. So this is not REST API server issue. The error message is "Failed to authenticate..", so there is something wrong with authentication. Can you also check if it works well with a different value with the same instance/bundle/user/pass?

**Comment by srl295** [comment]
I wasn't able to reproduce with the above file (renamed to `boxDrawingChars.json`).

```
> var bdc = require('/Users/srl/Downloads/boxDrawingChars.json');
> bdc
{ msgBoxDrawingChars: '└──' }
> b.uploadStrings({languageId: 'en', strings: bdc}, console.log);
null { status: 'SUCCESS' }
> b.getResourceStrings({languageId: 'en'}, console.log);
null { status: 'SUCCESS',
  resourceStrings: { msgBoxDrawingChars: '└──' },
  updatedAt: '2016-07-26T20:45:23.807Z' }
```

**Comment by yumaoka** [comment]
GP authentication is date sensitive. When a client system's clock is different from REST server more than 10 minutes, then the generated authentication code is invalidated. Can you check the client system's clock is accurate?

**Comment by srl295** [comment]
The bug is  in fact due to https://github.com/nodejs/node/issues/5499#issuecomment-190493397 — apparently `update()` takes an encoding param.

**Comment by srl295** [comment]
so according to https://nodejs.org/api/crypto.html#crypto_hmac_update_data_input_encoding the default is utf-8 , but this wasn't true in previous node versions.
