### ISSUE TITLE
Space characters around placeholder curly brackets

### ISSUE THREAD

**Issue by Setogit** [IBM-Bluemix/gp-js-client#6]
What’s the rule of adding/removing U+0020 space characters around placeholder curly brackets in Globalization Pipeline on Bluemix?  For example,
en: "Version {phVersion}”
is translated to the following:
de: "Version {phVersion}”
es: "Versión { phVersion }”
fr: "Version de { phVersion }”
it: "Versione {phVersion}”
ja: "バージョン{phVersion}”
ko: "버전 {phVersion}”
pt-BR: "Versão { phVersion }”
zh-Hans: "版本{phVersion}”
zh-Hant: "版本{phVersion}”

Ideally, I’d like it to be consistent (don’t add/remove the space char) across languages

**Comment by srl295** [comment]
This is a comment pertaining to the service and not to this SDK specifically. Closing this in favor of the SO question http://stackoverflow.com/questions/34010795/placeholder-handling-in-ibm-bluemix-globalization-pipeline
